---
title: "Erick David Rodriguez-Orduna, B.E.E."
output:
    html_document:
        df_print: paged
---

Hello and welcome to my website.

I'm Erick David Rodriguez-Orduna, Bachelor of Electronical Engineering from Universidad de las Americas Puebla [UDLAP](https://www.udlap.mx/web){target="_blank"}

Currently I'm pursuing the Ph.D in Intelligent Systems from same institution.

In this website I will include some my work as a PhD student, which can be related or not related to the Doctoral Thesis topic.

Since my Doctoral program is a Full-Time study I don't have enough time to develop another projects but I also have strong interest in Data-Science and Economical-Finance areas, therefore I will also upload some of that work too.

I have experience coding in some programming languages:


*Experienced:*

- Python
- R

*Not that experienced:*

- C++
- SQL
- MATLAB
- Mosel from XPRESS
- Verilog
- Java
- JS







*Some of my Tutorials:*

- Bitso API.  In the video below you can find a brief tutorial on how to get current BTC price from the API of [BITSO EXCHANGE](bitso.com){target="_blank"} it also considers a Volume-Weighted Average Price (VWAP) that gets the price depending on the volume of bids and asks.\n
In spanish is PPP (Precio Promedio Ponderado) which is used by the Mexican Stock Exchange and that I considered as an accurate metric for real price of a stock.
```{r echo = FALSE}
library(tweetrmd)
tweet_embed("https://twitter.com/David_Rod_Ord/status/1476025484492390402?cxt=HHwWhIC-qfPW8vsoAAAA")
```
Another file in site [NB](/website.nb.html)



